name: CI (C++ & Python)

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev build-essential

      - name: Build GTest
        run: |
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo cp -v lib/*.a /usr/lib

      - name: Build project
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          # Make the binary executable and available in PATH
          chmod +x ascii85
          echo "$(pwd)" >> $GITHUB_PATH

      - name: Run C++ tests
        run: |
          cd build
          ./tests

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pytest
        run: |
          pip install pytest

      - name: Run Python tests
        run: |
          # Verify the binary is accessible
          which ascii85 || ls -l build/ascii85
          pytest test.py -v